-- DROP PRE OCUUPIED DATABASE
SELECT
	PG_TERMINATE_BACKEND(PG_STAT_ACTIVITY.PID)
FROM
	PG_STAT_ACTIVITY
WHERE
	DATNAME = 'MYDATA'
	AND PID <> PG_BACKEND_PID();

DROP DATABASE MYDATA;

DROP DATABASE MYDATA
WITH
	(FORCE);

-- ADD COLUMNS
CREATE TABLE PERSONS (
	PERSON_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL
);

ALTER TABLE PERSONS
ADD COLUMN AGE INT NOT NULL;

SELECT
	*
FROM
	PERSONS;

ALTER TABLE PERSONS
ADD COLUMN EMAIL VARCHAR(100) UNIQUE,
ADD COLUMN NATIONALITY VARCHAR(20) NOT NULL;

SELECT
	*
FROM
	PERSONS;

-- RENAME TABLE
ALTER TABLE USERS
RENAME TO PERSONS;

-- RENAME COLUMN
ALTER TABLE PERSONS
RENAME COLUMN PERSON_AGE TO AGE;

-- DROP COLUMN
ALTER TABLE PERSONS
DROP COLUMN AGE;

ALTER TABLE PERSONS
ADD COLUMN AGE VARCHAR(10) NOT NULL;

-- CHANGE THE DATA TYPE OF A COLUMN
ALTER TABLE PERSONS
ALTER COLUMN AGE TYPE INT USING AGE::INTEGER;

ALTER TABLE PERSONS
ALTER COLUMN AGE TYPE VARCHAR(20);

-- SET DEFAULT VALUE OF COLUMN
ALTER TABLE PERSONS
ADD COLUMN IS_ENABLE BOOLEAN;

ALTER TABLE PERSONS
ALTER COLUMN IS_ENABLE
SET DEFAULT FALSE;

INSERT INTO
	PERSONS (FIRST_NAME, LAST_NAME, EMAIL, NATIONALITY, AGE)
VALUES
	('JOHN', 'BENJAMIN', 'A@B.com', 'USA', 40);

SELECT
	*
FROM
	PERSONS;

ALTER TABLE PERSONS
ALTER COLUMN IS_ENABLE
SET DEFAULT 'Y';

-- ADD CONSTRAINTS TO COLUMN
CREATE TABLE WEB_LINKS (
	LINK_ID SERIAL PRIMARY KEY,
	LINK_URL VARCHAR(255) NOT NULL,
	LINK_TARGET VARCHAR(20)
);

INSERT INTO
	WEB_LINKS (LINK_URL, LINK_TARGET, IS_ENABLE)
VALUES
	('https://www.omegle.com', '_blank', 'N');

SELECT
	*
FROM
	WEB_LINKS;

ALTER TABLE WEB_LINKS
ADD CONSTRAINT "Unique Web Url" UNIQUE (LINK_URL);

ALTER TABLE WEB_LINKS
ADD COLUMN IS_ENABLE VARCHAR(2);

ALTER TABLE WEB_LINKS
ADD CHECK (IS_ENABLE IN ('Y', 'N'));