-- USING PGADMIN GUI : CREATE A DATABASE mydata
-- USING PGADMIN GUI : CREATE A TABLE accounts
SELECT
	*
FROM
	ACCOUNTS;

-- USING PGADMIN GUI : VIEW TABLE STRUCTURE
-- USING PGADMIN GUI : CREATE A COLUMN 
-- USING PGADMIN GUI : RENAME A COLUMN 
-- USING PGADMIN GUI : DROP / DELETE A COLUMN
-- USING PGADMIN GUI : CHANGE DATA TYPE OF A COLUMN
-- DELETING TABLES FROM A DATABASE
CREATE TABLE ROLES (
	ROLE_ID SERIAL PRIMARY KEY,
	ROLE_NAME VARCHAR(100)
);

SELECT
	*
FROM
	ROLES;

-- USING PGADMIN GUI : DELETE A TABLE
DROP TABLE IF EXISTS ROLES;