----------------------------------------------------------------------------------------------------
-- 	CREATE A CURRENCY ENUM DATA TYPE
CREATE TYPE CURRENCY AS ENUM('USD', 'EUR', 'INR');

ALTER TYPE CURRENCY
ADD VALUE 'GBP';

SELECT
	'USD'::CURRENCY;

ALTER TYPE CURRENCY
ADD VALUE 'CHF'
AFTER 'EUR';

CREATE TABLE STOCKS (
	STOCK_ID SERIAL PRIMARY KEY,
	STOCK_CURRENCY CURRENCY
);

INSERT INTO
	STOCKS (STOCK_CURRENCY)
VALUES
	('USD');

SELECT
	*
FROM
	STOCKS;

INSERT INTO
	STOCKS (STOCK_CURRENCY)
VALUES
	('ABC');

INSERT INTO
	STOCKS (STOCK_CURRENCY)
VALUES
	('CHF');

CREATE TYPE SAMPLE_TYPE AS ENUM('ABC', '123');

-- DROP A COMPOSITE TYPE
DROP TYPE SAMPLE_TYPE;

----------------------------------------------------------------------------------------------------
-- ALTER A COMPOSITE TYPE 
CREATE TYPE MYADDRESS AS (CITY VARCHAR(50), COUNTRY VARCHAR(20));

ALTER TYPE MYADDRESS
RENAME TO MY_ADDRESS;

ALTER TYPE MY_ADDRESS OWNER TO "DEEP";

ALTER TYPE MY_ADDRESS
SET SCHEMA TEST_SCM;

ALTER TYPE TEST_SCM.MY_ADDRESS
ADD ATTRIBUTE STREET_ADDRESS VARCHAR(150);

----------------------------------------------------------------------------------------------------
-- ALTER AN ENUM DATA TYPE
CREATE TYPE MY_COLORS AS ENUM('GREEN', 'RED', 'YELLOW', 'PINK');

-- RENAME A VALUE
ALTER TYPE MY_COLORS
RENAME VALUE 'RED' TO 'ORANGE';

-- LIST ALL ENUM VALUES
SELECT
	ENUM_RANGE(NULL::MY_COLORS);

-- ADD A VALUE
ALTER TYPE MY_COLORS
ADD VALUE 'RED'
AFTER 'GREEN';

----------------------------------------------------------------------------------------------------
-- UPDATE AN ENUM DATA IN PRODUCTION SERVER
CREATE TYPE STATUS_ENUM AS ENUM('QUEED', 'WAITING', 'RUNNING');

ALTER TYPE STATUS_ENUM
RENAME VALUE 'QUEED' TO 'QUEUED';

CREATE TABLE JOBS (JOB_ID SERIAL PRIMARY KEY, JOB_STATUS STATUS_ENUM);

INSERT INTO
	JOBS (JOB_STATUS)
VALUES
	('QUEUED');

SELECT
	ENUM_RANGE(NULL::STATUS_ENUM);

SELECT
	*
FROM
	JOBS;

INSERT INTO
	JOBS (JOB_STATUS)
VALUES
	('RUNNING');

UPDATE JOBS
SET
	JOB_STATUS = 'RUNNING';

ALTER TYPE STATUS_ENUM
RENAME TO STATUS_ENUM_OLD;

CREATE TYPE STATUS_ENUM AS ENUM('QUEED', 'RUNNING', 'DONE');

ALTER TABLE JOBS
ALTER COLUMN JOB_STATUS TYPE STATUS_ENUM USING JOB_STATUS::TEXT::STATUS_ENUM;

DROP TYPE STATUS_ENUM_OLD;

----------------------------------------------------------------------------------------------------
-- ENUM TYPE WITH DEFAULT VALUE
CREATE TYPE STATUS AS ENUM('PENDING', 'APPROVED', 'DECLINED');

CREATE TABLE CRON_JOBS (CRON_JOB_ID INT, STATUS STATUS);

ALTER TABLE CRON_JOBS
ALTER COLUMN STATUS SET DEFAULT 'PENDING';

INSERT INTO CRON_JOBS (CRON_JOB_ID, STATUS) VALUES (2, 'DECLINED');

SELECT * FROM CRON_JOBS;