-- CREATE TYPE IF NOT EXISTS USING PL/PGSQL FUNCTION
DO $$
BEGIN
	IF NOT EXISTS (SELECT * FROM PG_TYPE AS TYP
					INNER JOIN PG_NAMESPACE AS NSP
					ON NSP.OID = TYP.TYPNAMESPACE
					WHERE NSP.NSPNAME = CURRENT_SCHEMA()
							AND TYP.TYPNAME = 'AI') THEN
		CREATE TYPE AI AS (
			A TEXT,
			I INTEGER
		);
	END IF;
END;
$$ LANGUAGE PLPGSQL;