----------------------------------------------------------------------------------------------------
-- FULL Joins
-- RETURNS ALL THE DATA FROM TABLE1 AND TABLE2
SELECT
	*
FROM
	LEFT_PRODUCTS
	FULL JOIN RIGHT_PRODUCTS USING (PRODUCT_ID);

SELECT
	DR.FIRST_NAME || ' ' || DR.LAST_NAME AS "Director Name",
	COALESCE(MV.MOVIE_NAME, '')
FROM
	MOVIES AS MV
	FULL JOIN DIRECTORS AS DR USING (DIRECTOR_ID)
ORDER BY
	1;

SELECT
	DR.FIRST_NAME || ' ' || DR.LAST_NAME AS "Director Name",
	COALESCE(MV.MOVIE_NAME, ''),
	COALESCE(MV.MOVIE_LANGUAGE, '')
FROM
	MOVIES AS MV
	FULL JOIN DIRECTORS AS DR USING (DIRECTOR_ID)
WHERE
	MOVIE_LANGUAGE IN ('English', 'Chinese')
ORDER BY
	3,
	1;