-- || OPERATOR
SELECT
	'Hello' || ' ' || 'World' AS NEW_STRING;

SELECT
	FIRST_NAME || ' ' || LAST_NAME AS "Actor Name"
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC,
	LAST_NAME ASC;

SELECT
	FIRST_NAME || ', ' || LAST_NAME || ', ' || DATE_OF_BIRTH
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC;

SELECT
	'Hello' || NULL || 'World';

-- CONCAT FUNCTION
SELECT
	CONCAT('Hello', 'World') AS NEW_STRING;

SELECT
	CONCAT(FIRST_NAME, ' ', LAST_NAME) AS "Actor Name"
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC,
	LAST_NAME ASC;

SELECT
	CONCAT(FIRST_NAME, ', ', LAST_NAME, ', ', DATE_OF_BIRTH)
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC;

SELECT
	REVENUES_DOMESTIC,
	REVENUES_INTERNATIONAL,
	CONCAT(REVENUES_DOMESTIC, ' | ', REVENUES_INTERNATIONAL) AS "Profits"
FROM
	MOVIES_REVENUES;

SELECT
	CONCAT(REVENUES_DOMESTIC, ' | ', REVENUES_INTERNATIONAL) AS "Profits"
FROM
	MOVIES_REVENUES;


-- CONCAT_WS FUNCTION
SELECT
	CONCAT_WS('|', 'Hello', 'World') AS NEW_STRING;

SELECT
	CONCAT_WS(' ', FIRST_NAME, LAST_NAME) AS "Actor Name"
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC;

SELECT
	CONCAT_WS(', ', FIRST_NAME, LAST_NAME, DATE_OF_BIRTH)
FROM
	ACTORS
ORDER BY
	FIRST_NAME ASC;

SELECT
	REVENUES_DOMESTIC,
	REVENUES_INTERNATIONAL,
	CONCAT_WS(' | ', REVENUES_DOMESTIC, REVENUES_INTERNATIONAL)  "Profits"
FROM
	MOVIES_REVENUES;