----------------------------------------------------------------------------------------------------
-- COUNT
SELECT
	COUNT(*)
FROM
	MOVIES;

SELECT
	*
FROM
	MOVIES;

SELECT
	COUNT(MOVIE_LENGTH)
FROM
	MOVIES;

-- SELECT DISTINCT COUNT(MOVIE_LENGTH) FROM MOVIES; NOT THIS
SELECT
	COUNT(DISTINCT (MOVIE_LENGTH))
FROM
	MOVIES;

-- THIS ONE
SELECT
	COUNT(DISTINCT (DIRECTOR_ID))
FROM
	MOVIES;

SELECT
	COUNT(*)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	COUNT(MOVIE_NAME)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

----------------------------------------------------------------------------------------------------
-- Sum with SUM function
SELECT
	*
FROM
	MOVIES_REVENUES;

SELECT
	REVENUES_DOMESTIC
FROM
	MOVIES_REVENUES
ORDER BY
	REVENUES_DOMESTIC NULLS LAST;

SELECT
	SUM(REVENUES_DOMESTIC)
FROM
	MOVIES_REVENUES;

SELECT
	SUM(MOVIE_LENGTH)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	SUM(MOVIE_NAME)
FROM
	MOVIES;

SELECT
	SUM(MOVIE_NAME)
FROM
	MOVIES;

SELECT
	SUM(DISTINCT REVENUES_DOMESTIC)
FROM
	MOVIES_REVENUES;

----------------------------------------------------------------------------------------------------
-- MIN and MAX functions
SELECT
	MOVIE_LENGTH
FROM
	MOVIES
ORDER BY
	MOVIE_LENGTH DESC;

SELECT
	MOVIE_LENGTH,
	MAX(MOVIE_LENGTH)
FROM
	MOVIES
GROUP BY
	(MOVIE_LENGTH);

SELECT
	MAX(MOVIE_LENGTH)
FROM
	MOVIES;

SELECT
	MIN(MOVIE_LENGTH)
FROM
	MOVIES;

SELECT
	MAX(MOVIE_LENGTH)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	MAX(RELEASE_DATE)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	MAX(MOVIE_NAME)
FROM
	MOVIES;

SELECT
	MIN(RELEASE_DATE)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'Chinese';

----------------------------------------------------------------------------------------------------
-- GREATEST AND LEAST functions
-- LIST SHOULD BE OF COMMON DATA TYPE
SELECT
	LEAST('A', 'B', 'C');

SELECT
	GREATEST('A', 'B', 'C');

SELECT
	MOVIE_ID,
	REVENUES_DOMESTIC,
	REVENUES_INTERNATIONAL,
	GREATEST(REVENUES_DOMESTIC, REVENUES_INTERNATIONAL) "GREATEST",
	LEAST(REVENUES_DOMESTIC, REVENUES_INTERNATIONAL) "LEAST"
FROM
	MOVIES_REVENUES
ORDER BY
	4 ASC,
	5 ASC;

----------------------------------------------------------------------------------------------------
-- Average with AVG function
SELECT
	AVG(MOVIE_LENGTH)
FROM
	MOVIES;

SELECT
	AVG(MOVIE_LENGTH)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	AVG(DISTINCT (MOVIE_LENGTH))
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

SELECT
	AVG(MOVIE_NAME)
FROM
	MOVIES;

SELECT
	AVG(MOVIE_LENGTH),
	SUM(MOVIE_LENGTH)
FROM
	MOVIES
WHERE
	MOVIE_LANGUAGE = 'English';

----------------------------------------------------------------------------------------------------
-- Combining Columns using Mathematical operators
SELECT
	MOVIE_ID,
	REVENUES_DOMESTIC,
	REVENUES_INTERNATIONAL,
	(REVENUES_DOMESTIC + REVENUES_INTERNATIONAL) TOTAL_REVENUE
FROM
	MOVIES_REVENUES
WHERE
	(REVENUES_DOMESTIC + REVENUES_INTERNATIONAL) IS NOT NULL
ORDER BY
	4 DESC NULLS LAST;

SHOW DATESTYLE;